### ISSUE TITLE
Unexpected undefined object at xin-for template using computed prop

### ISSUE THREAD

**Issue by januarsiregar** [xinix-technology/xin#36]
```js
<xin-for items="[[foos]]" as="foo">
  <template>
    <pre>[[computeFoo(foo)]]</pre>
  </template>
</xin-for>
```

**Comment by reekoheek** [comment]
I suspect this is occured because computed function always run even when value is undefined. For the purpose of updating computed value when value is undefined.

So, it is expected behavior
